### ISSUE TITLE
Travis CI: reorder to speed up detection of first error

### ISSUE THREAD

**Issue by vlcinsky** [nameko/nameko#630]
Currently, travis runs large set of tests and it takes quite some time.

It would be great, if time to detection of first error could be shorter.

Currently it e.g. builds documentation which could be safely postponed as i assume, most development happens with code and not with the docs.

My proposal for order of initial test environments is:

```yaml
matrix:
  include:
# start with most popular predictable env. (py36)
## first detect functional issues and coverage problems
    - stage: test
      python: 3.6
      env: TOX_ENV=py36-pinned-lib
## then do static checks
    - stage: static
      python: 3.6
      env: TOX_ENV=py36-static
# repeat for py27
## first detect functional issues and coverage problems
    - stage: test
      python: 2.7
      env: TOX_ENV=py27-pinned-lib
## then do static checks
    - stage: static
      python: 2.7
      env: TOX_ENV=py27-static
# Build the docs
    - stage: docs
      python: 2.7
      env: TOX_ENV=docs
# Continue with whatever seems relevant

```
