### ISSUE TITLE
block question

### ISSUE THREAD

**Issue by panla** [nameko/nameko#720]
`config.yaml`

```yaml
AMQP_URI: 'pyamqp://root:root@127.0.0.1:5672'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
rpc_exchange: 'algo-rpc'
max_workers: 10
parent_calls_tracked: 10
```

`flask main.py`

```python
from flask import Flask
from flask import jsonify
from nameko.standalone.rpc import ClusterRpcProxy

app = Flask(__name__)

CONFIG = {'AMQP_URI': "pyamqp://root:root@127.0.0.1:5672"}

@app.route('/index', methods=['GET'])
def index():
    with ClusterRpcProxy(CONFIG) as rpc:
        result = rpc.TestService.say(msg='name is 123')
    return jsonify({'result': result})

if __name__ == '__main__':
    app.run(debug=True, host='127.0.0.1', port=8000)
```

if `rpc_exchange` in config and `rpc_exchange` != 'nameko_rpc',

then GET `http://127.0.0.1:8000/index` it is block

And what is the right and best func to run it?
